apiVersion: v1
kind: Service
metadata:
  name: seldon-service-lb
  namespace: seldon-system
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: grafana
  ports:
  - port: 3000
    targetPort: 3000